seed: 1

type: fed
mode: train

epochs: 10
num_users: 100
frac: 0.1
local_ep: 10
local_bs: 10
momentum: 0.5

model: cnn-mnist
num_channels: 1
norm: batch-norm
num_filter: 32
max_pool: True

dataset: mnist
num_classes: 10
optimiser: sgd
stopping_rounds: 10 
