seed: 1

type: fed
mode: train

epochs: 10
num_users: 10
frac: 1
local_ep: 10
local_bs: 10
momentum: 0.5

model: cnn-mnist
num_channels: 1
num_filter: 32
max_pool: True

dataset: mnist
custom_non_iid: true
num_classes: 10
optimiser: sgd
stopping_rounds: 10 
